branch_whitelist = [ "main" ]
pre_bump_hooks = [
  "cargo build --release",
  "cargo set-version {{version}}",
  "cargo check --release",
  "git add :/Cargo.lock"
]
post_bump_hooks = [
  "git push",
  "git push {{version}}",
]

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
cog check
cargo fmt -v --all --check
cargo clippy
"""

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "FilippoGurioli/nirioly"
owner = "FilippoGurioli"
authors = [
  { username = "FilippoGurioli", signature = "Filippo Gurioli" }
]

[commit_types]
perf = { bump_minor = true }
docs = { bump_minor = true }
revert = { bump_minor = true }
