name: CI

on:
  push:
    branches:
      - main

# Ensure subsequent pushes don't overlap releases
concurrency:
  group: production-release
  cancel-in-progress: false

jobs:
  build-and-release:
    name: Check, Test, Build, and Release
    runs-on: ubuntu-26.04
    permissions:
      contents: write # needed for pushing tags and creating releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # fetches entire history so cog can calculate version changes

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-edit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-edit

      - name: Cargo Check
        run: cargo check --verbose

      - name: Cargo Build
        run: cargo build --release --verbose

      - name: Cargo Test
        run: cargo test --verbose

      - name: Get Current Version
        id: pre_version
        run: |
          echo "current=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')" >> $GITHUB_OUTPUT

      - name: Cocogitto Auto Bump
        id: cog_bump
        uses: cocogitto/cocogitto-action@v4
        with:
          command: bump
          args: --auto --skip-ci
          git-user: 'github-actions[bot]'
          git-user-email: '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Upload Build Artifact
        if: steps.cog_bump.outputs.version != steps.pre_version.outputs.current
        uses: actions/upload-artifact@v7
        with:
          name: nirioly-linux-amd64
          path: target/release/nirioly

      - name: Create GitHub Release
        if: steps.cog_bump.outputs.version != steps.pre_version.outputs.current
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.cog_bump.outputs.version }}
          files: target/release/nirioly
          body_path: CHANGELOG.md
